import { Country } from '@/domains/trip/types';

export const TICKET = {
    DEPARTURE_IATA: 'ICN',
};

export const FORM = {
    INITIAL: {
        tripTitle: '',
        country: '',
        startDate: '',
        endDate: '',
        hashtags: [],
    },
    TITLE: {
        DATE: '여행 기간 *',
        COUNTRY: '여행 국가 *',
        COUNTRY_DEFAULT: '여행 국가를 선택해주세요',
        TITLE: '여행 제목 *',
        TITLE_PLACEHOLDER: '여행 제목을 입력해주세요',
        HASHTAG: '해시태그 *',
    },
    HASHTAG_MENU: [
        '솔로트립', // 혼자만의 여행
        '커플여행', // 연인과의 여행
        '패밀리', // 가족 여행
        '힐링스팟', // 심신의 휴식을 위한 장소
        '로컬체험', // 현지인처럼 경험하는 여행
        '당일치기', // 짧지만 강렬한 하루 여행
        '인생뷰', // 멋진 전망이나 풍경
        '감성숙소', // 특별한 분위기의 숙박 장소
        '숨은명소', // 아직 알려지지 않은 장소
        '식도락여행', // 음식 중심의 여행
        '럭셔리모먼트', // 작은 사치를 즐기는 순간
    ],
};

export const DEFAULT_TICKET = {
    tripTitle: '나만의 특별한 여행 이야기를 시작해보세요',
    country: '🇰🇷/대한민국/SOUTH KOREA',
    startDate: String(new Date()),
    endDate: String(new Date()),
    hashtags: ['첫여행', '새로운시작', '설렘가득'],
};

export const WELCOME_TICKET_DATA = {
    tripKey: '',
    tripTitle: '첫 티켓이 발급되었습니다',
    country: '👋/트립티케/TRIP TYCHE',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    hashtags: ['나홀로', '버킷리스트', '계획무시'],
    imagesDate: [],
    ownerNickname: '',
};

// 각 국가의 대표 국제공항 IATA 코드를 1개씩 매핑한다.
// 선정 기준: (1) 수도 공항, (2) 수도 공항이 작거나 국제선이 부족한 경우 최대 국제선 허브.
// 예: 한국=ICN, 일본=NRT, 미국=JFK, 영국=LHR, 프랑스=CDG, 베트남=SGN, 태국=BKK
// 산마리노처럼 국내 공항이 없는 경우, 사실상 게이트웨이가 되는 인접국 공항(RMI)을 사용한다.
export const COUNTRIES: Country[] = [
    {
        emoji: '🇬🇭',
        nameKo: '가나',
        nameEn: 'GHANA',
        value: '🇬🇭/가나/GHANA',
        iata: 'ACC',
    },
    {
        emoji: '🇬🇷',
        nameKo: '그리스',
        nameEn: 'GREECE',
        value: '🇬🇷/그리스/GREECE',
        iata: 'ATH',
    },
    {
        emoji: '🇿🇦',
        nameKo: '남아프리카 공화국',
        nameEn: 'SOUTH AFRICA',
        value: '🇿🇦/남아프리카 공화국/SOUTH AFRICA',
        iata: 'JNB',
    },
    {
        emoji: '🇳🇱',
        nameKo: '네덜란드',
        nameEn: 'NETHERLANDS',
        value: '🇳🇱/네덜란드/NETHERLANDS',
        iata: 'AMS',
    },
    {
        emoji: '🇳🇴',
        nameKo: '노르웨이',
        nameEn: 'NORWAY',
        value: '🇳🇴/노르웨이/NORWAY',
        iata: 'OSL',
    },
    {
        emoji: '🇳🇿',
        nameKo: '뉴질랜드',
        nameEn: 'NEW ZEALAND',
        value: '🇳🇿/뉴질랜드/NEW ZEALAND',
        iata: 'AKL',
    },
    {
        emoji: '🇹🇼',
        nameKo: '대만',
        nameEn: 'TAIWAN',
        value: '🇹🇼/대만/TAIWAN',
        iata: 'TPE',
    },
    {
        emoji: '🇰🇷',
        nameKo: '대한민국',
        nameEn: 'SOUTH KOREA',
        value: '🇰🇷/대한민국/SOUTH KOREA',
        iata: 'ICN',
    },
    {
        emoji: '🇩🇰',
        nameKo: '덴마크',
        nameEn: 'DENMARK',
        value: '🇩🇰/덴마크/DENMARK',
        iata: 'CPH',
    },
    {
        emoji: '🇩🇴',
        nameKo: '도미니카 공화국',
        nameEn: 'DOMINICAN REPUBLIC',
        value: '🇩🇴/도미니카 공화국/DOMINICAN REPUBLIC',
        iata: 'SDQ',
    },
    {
        emoji: '🇩🇪',
        nameKo: '독일',
        nameEn: 'GERMANY',
        value: '🇩🇪/독일/GERMANY',
        iata: 'FRA',
    },
    {
        emoji: '🇱🇦',
        nameKo: '라오스',
        nameEn: 'LAOS',
        value: '🇱🇦/라오스/LAOS',
        iata: 'VTE',
    },
    {
        emoji: '🇷🇴',
        nameKo: '루마니아',
        nameEn: 'ROMANIA',
        value: '🇷🇴/루마니아/ROMANIA',
        iata: 'OTP',
    },
    {
        emoji: '🇱🇺',
        nameKo: '룩셈부르크',
        nameEn: 'LUXEMBOURG',
        value: '🇱🇺/룩셈부르크/LUXEMBOURG',
        iata: 'LUX',
    },
    {
        emoji: '🇲🇴',
        nameKo: '마카오',
        nameEn: 'MACAU',
        value: '🇲🇴/마카오/MACAU',
        iata: 'MFM',
    },
    {
        emoji: '🇲🇾',
        nameKo: '말레이시아',
        nameEn: 'MALAYSIA',
        value: '🇲🇾/말레이시아/MALAYSIA',
        iata: 'KUL',
    },
    {
        emoji: '🇲🇽',
        nameKo: '멕시코',
        nameEn: 'MEXICO',
        value: '🇲🇽/멕시코/MEXICO',
        iata: 'MEX',
    },
    {
        emoji: '🇲🇨',
        nameKo: '모나코',
        nameEn: 'MONACO',
        value: '🇲🇨/모나코/MONACO',
        iata: 'MCM',
    },
    {
        emoji: '🇲🇦',
        nameKo: '모로코',
        nameEn: 'MOROCCO',
        value: '🇲🇦/모로코/MOROCCO',
        iata: 'CMN',
    },
    {
        emoji: '🇲🇻',
        nameKo: '몰디브',
        nameEn: 'MALDIVES',
        value: '🇲🇻/몰디브/MALDIVES',
        iata: 'MLE',
    },
    {
        emoji: '🇺🇸',
        nameKo: '미국',
        nameEn: 'UNITED STATES',
        value: '🇺🇸/미국/UNITED STATES',
        iata: 'JFK',
    },
    {
        emoji: '🇧🇭',
        nameKo: '바레인',
        nameEn: 'BAHRAIN',
        value: '🇧🇭/바레인/BAHRAIN',
        iata: 'BAH',
    },
    {
        emoji: '🇧🇩',
        nameKo: '방글라데시',
        nameEn: 'BANGLADESH',
        value: '🇧🇩/방글라데시/BANGLADESH',
        iata: 'DAC',
    },
    {
        emoji: '🇻🇳',
        nameKo: '베트남',
        nameEn: 'VIETNAM',
        value: '🇻🇳/베트남/VIETNAM',
        iata: 'SGN',
    },
    {
        emoji: '🇧🇪',
        nameKo: '벨기에',
        nameEn: 'BELGIUM',
        value: '🇧🇪/벨기에/BELGIUM',
        iata: 'BRU',
    },
    {
        emoji: '🇧🇦',
        nameKo: '보스니아 헤르체고비나',
        nameEn: 'BOSNIA AND HERZEGOVINA',
        value: '🇧🇦/보스니아 헤르체고비나/BOSNIA AND HERZEGOVINA',
        iata: 'SJJ',
    },
    {
        emoji: '🇧🇷',
        nameKo: '브라질',
        nameEn: 'BRAZIL',
        value: '🇧🇷/브라질/BRAZIL',
        iata: 'GRU',
    },
    {
        emoji: '🇧🇳',
        nameKo: '브루나이',
        nameEn: 'BRUNEI',
        value: '🇧🇳/브루나이/BRUNEI',
        iata: 'BWN',
    },
    {
        emoji: '🇸🇦',
        nameKo: '사우디아라비아',
        nameEn: 'SAUDI ARABIA',
        value: '🇸🇦/사우디아라비아/SAUDI ARABIA',
        iata: 'RUH',
    },
    {
        emoji: '🇸🇲',
        nameKo: '산마리노',
        nameEn: 'SAN MARINO',
        value: '🇸🇲/산마리노/SAN MARINO',
        iata: 'RMI',
    },
    {
        emoji: '🇷🇸',
        nameKo: '세르비아',
        nameEn: 'SERBIA',
        value: '🇷🇸/세르비아/SERBIA',
        iata: 'BEG',
    },
    {
        emoji: '🇸🇨',
        nameKo: '세이셸',
        nameEn: 'SEYCHELLES',
        value: '🇸🇨/세이셸/SEYCHELLES',
        iata: 'SEZ',
    },
    {
        emoji: '🇱🇰',
        nameKo: '스리랑카',
        nameEn: 'SRI LANKA',
        value: '🇱🇰/스리랑카/SRI LANKA',
        iata: 'CMB',
    },
    {
        emoji: '🇸🇪',
        nameKo: '스웨덴',
        nameEn: 'SWEDEN',
        value: '🇸🇪/스웨덴/SWEDEN',
        iata: 'ARN',
    },
    {
        emoji: '🇨🇭',
        nameKo: '스위스',
        nameEn: 'SWITZERLAND',
        value: '🇨🇭/스위스/SWITZERLAND',
        iata: 'ZRH',
    },
    {
        emoji: '🇪🇸',
        nameKo: '스페인',
        nameEn: 'SPAIN',
        value: '🇪🇸/스페인/SPAIN',
        iata: 'MAD',
    },
    {
        emoji: '🇸🇬',
        nameKo: '싱가포르',
        nameEn: 'SINGAPORE',
        value: '🇸🇬/싱가포르/SINGAPORE',
        iata: 'SIN',
    },
    {
        emoji: '🇦🇪',
        nameKo: '아랍에미리트',
        nameEn: 'UNITED ARAB EMIRATES',
        value: '🇦🇪/아랍에미리트/UNITED ARAB EMIRATES',
        iata: 'DXB',
    },
    {
        emoji: '🇦🇷',
        nameKo: '아르헨티나',
        nameEn: 'ARGENTINA',
        value: '🇦🇷/아르헨티나/ARGENTINA',
        iata: 'EZE',
    },
    {
        emoji: '🇮🇸',
        nameKo: '아이슬란드',
        nameEn: 'ICELAND',
        value: '🇮🇸/아이슬란드/ICELAND',
        iata: 'KEF',
    },
    {
        emoji: '🇮🇪',
        nameKo: '아일랜드',
        nameEn: 'IRELAND',
        value: '🇮🇪/아일랜드/IRELAND',
        iata: 'DUB',
    },
    {
        emoji: '🇩🇿',
        nameKo: '알제리',
        nameEn: 'ALGERIA',
        value: '🇩🇿/알제리/ALGERIA',
        iata: 'ALG',
    },
    {
        emoji: '🇪🇪',
        nameKo: '에스토니아',
        nameEn: 'ESTONIA',
        value: '🇪🇪/에스토니아/ESTONIA',
        iata: 'TLL',
    },
    {
        emoji: '🇪🇨',
        nameKo: '에콰도르',
        nameEn: 'ECUADOR',
        value: '🇪🇨/에콰도르/ECUADOR',
        iata: 'UIO',
    },
    {
        emoji: '🇬🇧',
        nameKo: '영국',
        nameEn: 'UNITED KINGDOM',
        value: '🇬🇧/영국/UNITED KINGDOM',
        iata: 'LHR',
    },
    {
        emoji: '🇴🇲',
        nameKo: '오만',
        nameEn: 'OMAN',
        value: '🇴🇲/오만/OMAN',
        iata: 'MCT',
    },
    {
        emoji: '🇦🇺',
        nameKo: '오스트레일리아',
        nameEn: 'AUSTRALIA',
        value: '🇦🇺/오스트레일리아/AUSTRALIA',
        iata: 'SYD',
    },
    {
        emoji: '🇦🇹',
        nameKo: '오스트리아',
        nameEn: 'AUSTRIA',
        value: '🇦🇹/오스트리아/AUSTRIA',
        iata: 'VIE',
    },
    {
        emoji: '🇺🇾',
        nameKo: '우루과이',
        nameEn: 'URUGUAY',
        value: '🇺🇾/우루과이/URUGUAY',
        iata: 'MVD',
    },
    {
        emoji: '🇺🇦',
        nameKo: '우크라이나',
        nameEn: 'UKRAINE',
        value: '🇺🇦/우크라이나/UKRAINE',
        iata: 'KBP',
    },
    {
        emoji: '🇮🇶',
        nameKo: '이라크',
        nameEn: 'IRAQ',
        value: '🇮🇶/이라크/IRAQ',
        iata: 'BGW',
    },
    {
        emoji: '🇮🇱',
        nameKo: '이스라엘',
        nameEn: 'ISRAEL',
        value: '🇮🇱/이스라엘/ISRAEL',
        iata: 'TLV',
    },
    {
        emoji: '🇪🇬',
        nameKo: '이집트',
        nameEn: 'EGYPT',
        value: '🇪🇬/이집트/EGYPT',
        iata: 'CAI',
    },
    {
        emoji: '🇮🇹',
        nameKo: '이탈리아',
        nameEn: 'ITALY',
        value: '🇮🇹/이탈리아/ITALY',
        iata: 'FCO',
    },
    {
        emoji: '🇮🇳',
        nameKo: '인도',
        nameEn: 'INDIA',
        value: '🇮🇳/인도/INDIA',
        iata: 'DEL',
    },
    {
        emoji: '🇮🇩',
        nameKo: '인도네시아',
        nameEn: 'INDONESIA',
        value: '🇮🇩/인도네시아/INDONESIA',
        iata: 'CGK',
    },
    {
        emoji: '🇯🇵',
        nameKo: '일본',
        nameEn: 'JAPAN',
        value: '🇯🇵/일본/JAPAN',
        iata: 'NRT',
    },
    {
        emoji: '🇯🇲',
        nameKo: '자메이카',
        nameEn: 'JAMAICA',
        value: '🇯🇲/자메이카/JAMAICA',
        iata: 'KIN',
    },
    {
        emoji: '🇬🇪',
        nameKo: '조지아',
        nameEn: 'GEORGIA',
        value: '🇬🇪/조지아/GEORGIA',
        iata: 'TBS',
    },
    {
        emoji: '🇨🇿',
        nameKo: '체코',
        nameEn: 'CZECH REPUBLIC',
        value: '🇨🇿/체코/CZECH REPUBLIC',
        iata: 'PRG',
    },
    {
        emoji: '🇨🇱',
        nameKo: '칠레',
        nameEn: 'CHILE',
        value: '🇨🇱/칠레/CHILE',
        iata: 'SCL',
    },
    {
        emoji: '🇨🇲',
        nameKo: '카메룬',
        nameEn: 'CAMEROON',
        value: '🇨🇲/카메룬/CAMEROON',
        iata: 'DLA',
    },
    {
        emoji: '🇰🇿',
        nameKo: '카자흐스탄',
        nameEn: 'KAZAKHSTAN',
        value: '🇰🇿/카자흐스탄/KAZAKHSTAN',
        iata: 'ALA',
    },
    {
        emoji: '🇶🇦',
        nameKo: '카타르',
        nameEn: 'QATAR',
        value: '🇶🇦/카타르/QATAR',
        iata: 'DOH',
    },
    {
        emoji: '🇰🇭',
        nameKo: '캄보디아',
        nameEn: 'CAMBODIA',
        value: '🇰🇭/캄보디아/CAMBODIA',
        iata: 'PNH',
    },
    {
        emoji: '🇨🇦',
        nameKo: '캐나다',
        nameEn: 'CANADA',
        value: '🇨🇦/캐나다/CANADA',
        iata: 'YYZ',
    },
    {
        emoji: '🇰🇪',
        nameKo: '케냐',
        nameEn: 'KENYA',
        value: '🇰🇪/케냐/KENYA',
        iata: 'NBO',
    },
    {
        emoji: '🇨🇷',
        nameKo: '코스타리카',
        nameEn: 'COSTA RICA',
        value: '🇨🇷/코스타리카/COSTA RICA',
        iata: 'SJO',
    },
    {
        emoji: '🇨🇴',
        nameKo: '콜롬비아',
        nameEn: 'COLOMBIA',
        value: '🇨🇴/콜롬비아/COLOMBIA',
        iata: 'BOG',
    },
    {
        emoji: '🇰🇼',
        nameKo: '쿠웨이트',
        nameEn: 'KUWAIT',
        value: '🇰🇼/쿠웨이트/KUWAIT',
        iata: 'KWI',
    },
    {
        emoji: '🇭🇷',
        nameKo: '크로아티아',
        nameEn: 'CROATIA',
        value: '🇭🇷/크로아티아/CROATIA',
        iata: 'ZAG',
    },
    {
        emoji: '🇹🇭',
        nameKo: '태국',
        nameEn: 'THAILAND',
        value: '🇹🇭/태국/THAILAND',
        iata: 'BKK',
    },
    {
        emoji: '🇹🇷',
        nameKo: '터키',
        nameEn: 'TURKEY',
        value: '🇹🇷/터키/TURKEY',
        iata: 'IST',
    },
    {
        emoji: '🇵🇦',
        nameKo: '파나마',
        nameEn: 'PANAMA',
        value: '🇵🇦/파나마/PANAMA',
        iata: 'PTY',
    },
    {
        emoji: '🇵🇾',
        nameKo: '파라과이',
        nameEn: 'PARAGUAY',
        value: '🇵🇾/파라과이/PARAGUAY',
        iata: 'ASU',
    },
    {
        emoji: '🇵🇰',
        nameKo: '파키스탄',
        nameEn: 'PAKISTAN',
        value: '🇵🇰/파키스탄/PAKISTAN',
        iata: 'ISB',
    },
    {
        emoji: '🇵🇪',
        nameKo: '페루',
        nameEn: 'PERU',
        value: '🇵🇪/페루/PERU',
        iata: 'LIM',
    },
    {
        emoji: '🇵🇹',
        nameKo: '포르투갈',
        nameEn: 'PORTUGAL',
        value: '🇵🇹/포르투갈/PORTUGAL',
        iata: 'LIS',
    },
    {
        emoji: '🇵🇱',
        nameKo: '폴란드',
        nameEn: 'POLAND',
        value: '🇵🇱/폴란드/POLAND',
        iata: 'WAW',
    },
    {
        emoji: '🇫🇷',
        nameKo: '프랑스',
        nameEn: 'FRANCE',
        value: '🇫🇷/프랑스/FRANCE',
        iata: 'CDG',
    },
    {
        emoji: '🇫🇮',
        nameKo: '핀란드',
        nameEn: 'FINLAND',
        value: '🇫🇮/핀란드/FINLAND',
        iata: 'HEL',
    },
    {
        emoji: '🇵🇭',
        nameKo: '필리핀',
        nameEn: 'PHILIPPINES',
        value: '🇵🇭/필리핀/PHILIPPINES',
        iata: 'MNL',
    },
    {
        emoji: '🇭🇺',
        nameKo: '헝가리',
        nameEn: 'HUNGARY',
        value: '🇭🇺/헝가리/HUNGARY',
        iata: 'BUD',
    },
    {
        emoji: '🇭🇰',
        nameKo: '홍콩',
        nameEn: 'HONG KONG',
        value: '🇭🇰/홍콩/HONG KONG',
        iata: 'HKG',
    },
];
